version: '3'
services:
  ganache-cli:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    volumes:
      - ganache-data:/data
    command: ganache-cli -a 1000 -e 1000 --db /data --mnemonic "muscle earn swing aim cheap protect voyage spare analyst little climb gas" --networkId 1719041703477
    networks:
      ganache-network:
        ipv4_address: "172.20.0.2"

  # Truffle service for initial migration only
  truffle:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - ganache-cli
    networks:
      - ganache-network
    entrypoint: /bin/sh -c "npm install -g truffle && truffle compile && truffle migrate --network development"
    # Automatically remove the container after it completes
    restart: "no"  # Ensures Truffle doesn’t restart
