version: '3'
services:
  ganache-cli:
    image: trufflesuite/ganache-cli
    ports:
      - "10009:8545"
    volumes:
      - ganache-data:/data
    command: ganache-cli -a 1000 -e 100 --db /data --mnemonic "muscle earn swing aim cheap protect voyage spare analyst little climb gas" --networkId 1719041703477
    networks:
      ganache-network:
        ipv4_address: 172.20.0.2

volumes:
  ganache-data:

networks:
  ganache-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
