version: '3'
services:
  ganache-cli:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    volumes:
      - ganache-data:/data
    command: ganache-cli -a 1000 -e 100 --db /data --mnemonic "muscle earn swing aim cheap protect voyage spare analyst little climb gas" --networkId 1719041703477
    networks:
      ganache-network:
        ipv4_address: 172.20.0.2

  # truffle:
  #   image: node:16
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - ganache-cli
  #   networks:
  #     - ganache-network
  #   entrypoint: /bin/sh -c "npm install -g truffle && truffle compile && truffle migrate --network development"


volumes:
  ganache-data:

networks:
  ganache-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
